<a href="https://colab.research.google.com/github/sharmila-Nri/Python-mini-project-/blob/main/INTRODUCTION_TO_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Nump-Numatic python
#Most powerful package-Libarary

#Numpy-Dimensions

#A- One Dimensional Array
#[A,B]|| [A
#.        B]-Two Dimensional Array-Row||colum
# Three Dimensional
#Array- Storing,Manipulating,similar Data type
#Faster than any mathematical functions
#convinient compared to other packages
#Memory efficiency
#support multi dimensional arras

#speed(Numpy operations)>speed(Lists operations)
#size(Numpy operations)<size(Lists operations)
#Memory Optimization (Numpy)>Memory Optimization (List operations)

In [ ]:
#Install numpy-pip3 install numpy||pip install numpy

In [ ]:
#create a numpy array
#1D array

arr1D=np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [ ]:
import numpy as np

In [ ]:
#creating 2D array-Matrix
arr2D=np.array([
     [0,0,0],[0,0,0]
])
print(arr2D)

[[0 0 0]
 [0 0 0]]


In [ ]:
#creating arrays with default values

allzeros=np.zeros((2,3))
print(allzeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating matrix with all values of elements as '1'
allOnes=np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#creating matrix with all values of elements as 'constants values-n~Fill values'
allconstant=np.full((2,3),6)
print(allconstant)

[[6 6 6]
 [6 6 6]]


In [ ]:
#create an identity matrix -I-squre matrix

identity =np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Identity Matrix - Aii= 1 && Aij=0
#For all A Belongs to R MxN
#Aij-

In [ ]:
#create a random Matrices

#with 0 and 1
rand1=np.random.rand(3,3)
print(rand1)

# between a and b
rand2=np.random.randint(10,20,(3,3))
print(rand2)

[[0.10851288 0.15615662 0.46461091]
 [0.61153047 0.67144852 0.30860833]
 [0.32380227 0.73174719 0.04966087]]
[[13 12 19]
 [19 13 18]
 [10 11 10]]


In [ ]:
#Array properties
arr=np.array([ [1,2,3,4],[2,3,4,5]])
print(arr)

# shape or array
print(f'\ n The shape of the array is ({arr.shape}')
#size of array
print(f'The size of the array is ({arr.size}')

#Datatype
print(f'The Data type of the array is { arr.dtype}')
#Dimentions of array
print(f'post The Dimension of the array is ({arr.ndim}')

[[1 2 3 4]
 [2 3 4 5]]
\ n The shape of the array is ((2, 4)
The size of the array is (8
The Data type of the array is int64
post The Dimension of the array is (2


In [ ]:
#Indexing and slicing

#Access the elements in 1D Array

arr=np. array([1,2,3,4])
print(arr)
print(arr[3])

#slicing the elements
print(arr[0:3])

#Access the element in 2D array
arr2=np.array([[1,2,3],[2,3,4]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:])#frist row with  all columns
print(arr2[:,0])#frist column with all tows

[1 2 3 4]
4
[1 2 3]
[[1 2 3]
 [2 3 4]]
3
[1 2 3]
[1 2]


In [ ]:
#l1=[]
# [l1.append(_) for_in range(10)]

l1=np.arange(10,-10,-1)

print(l1)

[10  9  8  7  6  5  4  3  2  1  0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [ ]:
#Mathematical operations

a=np.array([1,2,3])
b=np.array([3,4,5])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [4 6 8]
The diff of a and b is [-2 -2 -2]
The product of a and b is [ 3  8 15]
The division of a and b is [0.33333333 0.5        0.6       ]


In [ ]:
#Matrix multiplication
b1=np.array([[1,2,3],[2,3,4]])
b2=np.array([[5,6],[7,8],[1,3]])

#Dot product   ___ product=AB __ A m × n __ B n × p
C=np.dot(b1,b2)
print(C)

[[22 31]
 [35 48]]


In [ ]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [ ]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [ ]:
[
  [22,31],
  [35,48]
]

[[22, 31], [35, 48]]